### ISSUE TITLE
cab-0.2.19: Ambiguous occurrence ‘unPackageName’

### ISSUE THREAD

**Issue by juhp** [kazu-yamamoto/cab#39]
This may well be fixed in git but 0.2.19 fails to build with ghc-9.2.5:
```
Distribution/Cab/GenPaths.hs:35:14: error:
    Ambiguous occurrence ‘unPackageName’
    It could refer to
       either ‘Distribution.Cab.Utils.unPackageName’,
              imported from ‘Distribution.Cab.Utils’ at Distribution/Cab/GenPaths.hs:8:63-75
              (and originally defined at Distribution/Cab/Utils.hs:100:1-13)
           or ‘Distribution.PackageDescription.unPackageName’,
              imported from ‘Distribution.PackageDescription’ at Distribution/Cab/GenPaths.hs:10:1-38
              (and originally defined in ‘Distribution.Types.PackageName’)
   |
35 |         nm = unPackageName $ pkgName pkg
   |              ^^^^^^^^^^^^^
```
To be quite honest I don't use cab personally though we still have it packaged in Fedora.

I can try your recent commit anyway - but maybe you want to push a new release when you find time, thanks. :)

**Comment by kazu-yamamoto** [comment]
Would you try the current master?
If it fixes this problem, I should release a new version.

**Comment by juhp** [comment]
Yes, it build fine for me, Kazu-san, with ghc-9.2.5

**Comment by kazu-yamamoto** [comment]
I have released cab v0.2.20.
